// 🤖 自动生成的模块注册文件
// 此文件由构建工具自动生成，请勿手动编辑！
// 要更新此文件，请运行: dart tool/generate_modules.dart

import 'package:sakiengine/src/core/project_module_loader.dart';

// 自动发现的模块导入
import 'package:sakiengine/soranouta/soranouta_module.dart';

/// 自动生成的模块工厂映射表
final Map<String, GameModuleFactory> _autoGeneratedModules = {
  'soranouta': () => SoranoutaModule(),
};

/// 自动注册所有发现的模块
void registerAllDiscoveredModules() {
  final loader = ProjectModuleLoader();
  
  print('[GeneratedModuleRegistry] 🤖 开始注册自动发现的模块');
  
  for (final entry in _autoGeneratedModules.entries) {
    try {
      loader.registerModule(entry.key, entry.value);
      print('[GeneratedModuleRegistry] ✅ 注册模块: ${entry.key}');
    } catch (e) {
      print('[GeneratedModuleRegistry] ❌ 注册模块 ${entry.key} 失败: $e');
    }
  }
  
  print('[GeneratedModuleRegistry] 🎯 完成！已注册 ${_autoGeneratedModules.length} 个模块');
}
