#!/usr/bin/env dart
// 🤖 模块自动发现和注册表生成工具
// 用法: dart tool/generate_modules.dart

import 'dart:io';

void main() {
  print('🤖 开始自动生成模块注册表...');
  
  final generator = ModuleRegistryGenerator();
  generator.generateRegistry();
  
  print('✅ 模块注册表生成完成！');
}

class ModuleRegistryGenerator {
  void generateRegistry() {
    // 扫描所有可用模块
    final modules = _scanForModules();
    print('🔍 发现 ${modules.length} 个模块: ${modules.join(', ')}');
    
    // 生成注册表代码
    final code = _generateRegistryCode(modules);
    
    // 写入生成的文件
    final outputFile = File('lib/src/core/generated_module_registry.dart');
    outputFile.writeAsStringSync(code);
    
    print('📝 已生成: ${outputFile.path}');
  }
  
  List<String> _scanForModules() {
    final modules = <String>[];
    final libDir = Directory('lib');
    
    if (!libDir.existsSync()) {
      print('❌ lib 目录不存在');
      return modules;
    }
    
    for (final entity in libDir.listSync()) {
      if (entity is Directory) {
        final dirName = entity.path.split('/').last;
        
        // 跳过 src 目录和隐藏目录
        if (dirName == 'src' || dirName.startsWith('.')) continue;
        
        // 检查是否有对应的模块文件
        final moduleFile = File('${entity.path}/${dirName}_module.dart');
        if (moduleFile.existsSync()) {
          modules.add(dirName);
          print('🎯 找到模块: $dirName');
        }
      }
    }
    
    return modules;
  }
  
  String _generateRegistryCode(List<String> modules) {
    final buffer = StringBuffer();
    
    // 文件头部注释
    buffer.writeln('// 🤖 自动生成的模块注册文件');
    buffer.writeln('// 此文件由构建工具自动生成，请勿手动编辑！');
    buffer.writeln('// 要更新此文件，请运行: dart tool/generate_modules.dart');
    buffer.writeln();
    
    // 导入语句
    buffer.writeln('import \'package:sakiengine/src/core/project_module_loader.dart\';');
    buffer.writeln();
    
    if (modules.isNotEmpty) {
      buffer.writeln('// 自动发现的模块导入');
      for (final module in modules) {
        final className = _toPascalCase(module) + 'Module';
        buffer.writeln('import \'package:sakiengine/$module/${module}_module.dart\';');
      }
      buffer.writeln();
      
      // 模块映射表
      buffer.writeln('/// 自动生成的模块工厂映射表');
      buffer.writeln('final Map<String, GameModuleFactory> _autoGeneratedModules = {');
      for (final module in modules) {
        final className = _toPascalCase(module) + 'Module';
        buffer.writeln('  \'$module\': () => $className(),');
      }
      buffer.writeln('};');
    } else {
      buffer.writeln('// 未发现任何项目模块');
      buffer.writeln('final Map<String, GameModuleFactory> _autoGeneratedModules = <String, GameModuleFactory>{};');
    }
    
    buffer.writeln();
    
    // 注册函数
    buffer.writeln('/// 自动注册所有发现的模块');
    buffer.writeln('void registerAllDiscoveredModules() {');
    buffer.writeln('  final loader = ProjectModuleLoader();');
    buffer.writeln('  ');
    buffer.writeln('  print(\'[GeneratedModuleRegistry] 🤖 开始注册自动发现的模块\');');
    buffer.writeln('  ');
    buffer.writeln('  for (final entry in _autoGeneratedModules.entries) {');
    buffer.writeln('    try {');
    buffer.writeln('      loader.registerModule(entry.key, entry.value);');
    buffer.writeln('      print(\'[GeneratedModuleRegistry] ✅ 注册模块: \${entry.key}\');');
    buffer.writeln('    } catch (e) {');
    buffer.writeln('      print(\'[GeneratedModuleRegistry] ❌ 注册模块 \${entry.key} 失败: \$e\');');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln('  ');
    buffer.writeln('  print(\'[GeneratedModuleRegistry] 🎯 完成！已注册 \${_autoGeneratedModules.length} 个模块\');');
    buffer.writeln('}');
    
    return buffer.toString();
  }
  
  String _toPascalCase(String input) {
    return input.split('_')
        .map((word) => word.isEmpty ? '' : word[0].toUpperCase() + word.substring(1).toLowerCase())
        .join('');
  }
}